# Import the necessary libraries

In [3]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, mean_absolute_error
from sklearn.linear_model import Ridge,Lasso
from sklearn import metrics
import matplotlib.pyplot as plt
%matplotlib inline

# Import the dataset

In [6]:
house_data = pd.read_csv("https://raw.githubusercontent.com/edyoda/data-science-complete-tutorial/master/Data/house_rental_data.csv.txt")
house_data.head()

Unnamed: 0      Sqft  Floor  TotalFloor  Bedroom  Living.Room  Bathroom  \
0           1  1177.698      2           7        2            2         2   
1           2  2134.800      5           7        4            2         2   
2           3  1138.560      5           7        2            2         1   
3           4  1458.780      2           7        3            2         2   
4           5   967.776     11          14        3            2         2   

   Price  
0  62000  
1  78000  
2  58000  
3  45000  
4  45000

In [7]:
columns = house_data.columns.tolist()

In [8]:
columns.remove('Price')

In [9]:
feature_data = house_data[columns]
target_data = house_data.Price

In [10]:
X_train,X_test, y_train,y_test = train_test_split(feature_data, target_data)

In [11]:
X_train.shape

(483, 7)

In [12]:
X_test.shape

(162, 7)

In [13]:
lr = LinearRegression(normalize=True)

In [14]:
lr.fit(X_train,y_train)

C:\Users\91786\anaconda3\lib\site-packages\sklearn\linear_model\_base.py:141: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), LinearRegression())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)


  warnings.warn(


LinearRegression(normalize=True)

In [15]:
lr.coef_

array([   -4.95234051,    38.79928808,   956.52914368,    30.68081126,
       -2713.14069551, -3297.32091174,  2965.72841837])

In [16]:
X_test[:5]

Unnamed: 0      Sqft  Floor  TotalFloor  Bedroom  Living.Room  Bathroom
393         397  1366.272     10          12        3            2         2
499         503  1067.400      6           9        4            2         2
312         316  1515.708      2           7        2            2         2
554         558   889.500     11          18        2            2         1
295         299  1579.752     10          12        4            1         1

In [17]:
y_test[:5]

393    41000
499    50000
312    48800
554    30500
295    65000
Name: Price, dtype: int64

In [18]:
lr.predict(X_test[:5])

array([59039.73440008, 40287.46577578, 60146.38788437, 40632.01969125,
       65426.38758677])

In [19]:
pred = lr.predict(X_test)

In [20]:
mean_absolute_error(y_pred=pred, y_true=y_test)

13193.759272053883

In [21]:
ridge = Ridge(alpha=1000)
lasso = Lasso(alpha=1000)

In [22]:
ridge.fit(X_train,y_train)
lasso.fit(X_train,y_train)

Lasso(alpha=1000)

In [23]:
pred = ridge.predict(X_test)
pred = lasso.predict(X_test)

In [24]:
mean_absolute_error(y_pred=pred, y_true= y_test)

13370.30719894847

# Training the Data

In [35]:
from sklearn.model_selection import train_test_split

In [38]:
X = df[['Sqft', 'Floor', 'TotalFloor', 'Bedroom', 'Living.Room',
       'Bathroom']]
y = df["Price"]

In [39]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=0)    

# Using the Linear Regresson model

In [40]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
model = lr.fit(X_train,y_train)

# Predicting the data

In [43]:
y_pred = lr.predict(X_train)
y_pred

array([ 31861.60014074,  28571.79309799,  33056.96593822,  86880.75995654,
        90808.10783029,  80726.70630979,  85224.810976  ,  80917.26280855,
        37977.52197263,  53902.93312262,  70461.86982314,  70206.94245906,
        44714.20090695,  35978.13757212,  42710.70062172,  59678.72335914,
        27234.34892479, 114362.27484351, 119852.94871879,  57271.14244076,
        58492.25363346,  56825.88205766,  82890.88281876,  63309.4886439 ,
        44713.62820268,  50742.84338674,  61345.09493495,  69966.67835815,
        76505.86479018,  33522.86130001,  31797.06693114,  76289.18689311,
        91332.72451819,  36904.38675004,  42867.00701838,  75610.93205649,
       118294.02040737,  56881.27083346, 119852.94871879,  37630.52360181,
        29113.27104539,  58931.2925484 ,  58098.83689857,  60356.8541879 ,
        27520.39162338,  77920.56777736,  77166.53417331,  44993.67464978,
        69765.00372381,  52302.61616804, 100921.99081164, 110452.001459  ,
        50552.15141257,  

# Creating the Dataset for better understanding the actual and predicted data

In [44]:
predicted_dataframe = pd.DataFrame({"Actual_data" : y_train , "predicted_data" : y_pred})
predicted_dataframe

Actual_data  predicted_data
118        22000    31861.600141
235        36000    28571.793098
449        36000    33056.965938
175        82000    86880.759957
356        55000    90808.107830
..           ...             ...
9          65000    51926.023874
359        98000    80170.317513
192        75000    96029.805108
629        45000    61103.551897
559        35000    38307.621562

[483 rows x 2 columns]